FROM python:3.9

# install poetry

ENV POETRY_HOME /opt/poetry
ENV PATH ${POETRY_HOME}/bin:${PATH}
RUN apt-get update && apt-get install build-essential -y
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN poetry config virtualenvs.create false 

RUN mkdir /app
WORKDIR /app

# PLEASE KEEP IN MIND THAT THERE ARE POST-BUILD COMMANDS PROVIDED IN .devcontainer/devcontainer.json
